trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
    unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
  displayName: 'Download and install ChromeDriver'

- script: |
    source venv/bin/activate
    pytest --html=report.html --self-contained-html
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true
    testRunTitle: 'Python Selenium Tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'report.html'
    ArtifactName: 'TestReport'
  displayName: 'Publish test report'
