trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals MyWindowsAgent

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      curl -O https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_win32.zip
      tar -xvf chromedriver_win32.zip -C /usr/local/bin/
    displayName: 'Download and install ChromeDriver'

  - script: |
      venv\Scripts\activate
      pytest --html=report.html --self-contained-html
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-*.xml'
      mergeTestResults: true
      testRunTitle: 'Python Selenium Tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'report.html'
      ArtifactName: 'TestReport'
    displayName: 'Publish test report'
