trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals MyWindowsAgent

steps:
  - checkout: self

  # No need to set up Python if it's already installed on the agent

  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - powershell: |
      # Download ChromeDriver
      Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_win32.zip -OutFile chromedriver_win32.zip

      # Extract ChromeDriver
      Expand-Archive -Path chromedriver_win32.zip -DestinationPath .\

      # Check if the file already exists in the destination directory

      $destinationPath = "C:\Users\sanka\Desktop\chromedriver.exe"
      if (Test-Path $destinationPath) {
        # File already exists, rename or delete it
        # Rename-Item -Path $destinationPath -NewName "chromedriver_old.exe"
        Remove-Item -Path $destinationPath
        }

      # Move the chromedriver.exe file to the destination directory
      Move-Item -Path .\chromedriver.exe -Destination $destinationPath

    displayName: 'Download and install ChromeDriver'

  - script: |
      venv\Scripts\activate
      pytest --html=report.html --self-contained-html
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'  # Adjust the pattern to match your test result files
      testRunTitle: 'Test Results'


  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/report.html'
      ArtifactName: 'TestReport'
    displayName: 'Publish test report'


