trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals MyWindowsAgent

steps:
  - checkout: self

  # No need to set up Python if it's already installed on the agent

  - script: |
      python -m venv venv
      venv\Scripts\activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - powershell: |
      # Download ChromeDriver
      Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_win32.zip -OutFile chromedriver_win32.zip

      # Extract ChromeDriver
      Expand-Archive -Path chromedriver_win32.zip -DestinationPath .\

      # Move chromedriver.exe to a directory in PATH
      Move-Item -Path .\chromedriver.exe -Destination C:\Users\sanka\Desktop
    displayName: 'Download and install ChromeDriver'

  - script: |
      venv\Scripts\activate
      pytest --html=report.html --self-contained-html
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-*.xml'
      mergeTestResults: true
      testRunTitle: 'Python Selenium Tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'report.html'
      ArtifactName: 'TestReport'
    displayName: 'Publish test report'
